// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CurrentUnits {
  time: string;
  interval: string;
  temperature_2m: string;
  windspeed_10m: string;
  weathercode: string;
}
