// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Daily {
  time: Array<string>;
  temperature_2m_max: Array<number>;
  temperature_2m_min: Array<number>;
}
