// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Location } from "./Location";
import type { WeatherResponse } from "./WeatherResponse";

export interface WeatherData {
  weather_response: WeatherResponse;
  location: Location;
}
