// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Current } from "./Current";
import type { CurrentUnits } from "./CurrentUnits";
import type { Daily } from "./Daily";
import type { DailyUnits } from "./DailyUnits";
import type { Location } from "./Location";

export interface WeatherData {
  location: Location;
  current_units: CurrentUnits;
  current: Current;
  daily_units: DailyUnits;
  daily: Daily;
}
